name: Assignment 2 Testing with Jest

on: 
  pull_request:
    branches:
      - master
      - feedback
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [ 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM dependencies
        run: npm install
      - name: Run jest tests for tests
        run: npm run test
      - name: Build the project
        run: npm run build
      - name: Run the project
        run: npm run start &  
      - name: Wait 10s for the server to start
        run: sleep 10s
        shell: bash
      - name: Take Screenshot
        run: npm run take-screenshot-for-ci
      - name: Upload Screenshot to PR.
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: screenshot
          path: ci-screenshot.png
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for the submission
                [Output of the build (in downloaded zip)](${{ steps.artifact-upload-step.outputs.artifact-url }})
              `
            })

